<table>
	<tr><td>
		<?php 
			$this->form->getValue('CacheForm'); if(!$this->form->getValue('CacheForm')) echo $this->form ; 
		?>
	</td></tr>
	<tr><td>
		<table>
			<tr><td>
				<?php echo "<p>INDICE DE GENERATIVITE : nb d'item (".$this->NbItem.") / nb de cas (".$this->Potentiel.") => ".$this->NbItem/$this->Potentiel."</p>";?>
				<?php echo "<p>GENERATION :<br/>".$this->Generation."</p>";?>
				<?php echo "<p>DETAIL :<br/>".$this->Detail."</p>";?>
			</td></tr>
		</table>
	</td></tr>
</table>
			
			