/**
 * Bundled by jsDelivr using Rollup v2.79.2 and Terser v5.39.0.
 * Original file: /npm/@textcomplete/textarea@0.1.13/dist/index.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
import e from "../node_modules/undate/dist/index.js"; //"/npm/undate@0.3.0/+esm";
import t from "../node_modules/textarea-caret/index.js"; //"/npm/textarea-caret@3.1.0/+esm";
import i from "../node_modules/@textcomplete/core/dist/index.js"; //"/npm/@textcomplete/core@0.1.13/+esm";
import n from "../node_modules/@textcomplete/utils/dist/index.js"; //"/npm/@textcomplete/utils@0.1.13/+esm";
var s="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},o={},r={},l=s&&s.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(r,"__esModule",{value:!0}),r.TextareaEditor=void 0;const u=e,d=l(t),a=i,h=n;class p extends a.Editor{constructor(e){super(),this.el=e,this.onInput=()=>{this.emitChangeEvent()},this.onKeydown=e=>{const t=this.getCode(e);let i;"UP"===t||"DOWN"===t?i=this.emitMoveEvent(t):"ENTER"===t?i=this.emitEnterEvent():"ESC"===t&&(i=this.emitEscEvent()),i&&i.defaultPrevented&&e.preventDefault()},this.startListening()}destroy(){return super.destroy(),this.stopListening(),this}applySearchResult(e){const t=this.getBeforeCursor();if(null!=t){const i=e.replace(t,this.getAfterCursor());this.el.focus(),Array.isArray(i)&&((0,u.update)(this.el,i[0],i[1]),this.el&&this.el.dispatchEvent((0,a.createCustomEvent)("input")))}}getCursorOffset(){const e=(0,h.calculateElementOffset)(this.el),t=this.getElScroll(),i=this.getCursorPosition(),n=(0,h.getLineHeightPx)(this.el),s=e.top-t.top+i.top+n,o=e.left-t.left+i.left,r=this.el.getBoundingClientRect().top;if("rtl"!==this.el.dir)return{top:s,left:o,lineHeight:n,clientTop:r};return{top:s,right:document.documentElement?document.documentElement.clientWidth-o:0,lineHeight:n,clientTop:r}}getBeforeCursor(){return this.el.selectionStart!==this.el.selectionEnd?null:this.el.value.substring(0,this.el.selectionEnd)}getAfterCursor(){return this.el.value.substring(this.el.selectionEnd)}getElScroll(){return{top:this.el.scrollTop,left:this.el.scrollLeft}}getCursorPosition(){return(0,d.default)(this.el,this.el.selectionEnd)}startListening(){this.el.addEventListener("input",this.onInput),this.el.addEventListener("keydown",this.onKeydown)}stopListening(){this.el.removeEventListener("input",this.onInput),this.el.removeEventListener("keydown",this.onKeydown)}}r.TextareaEditor=p,function(e){Object.defineProperty(e,"__esModule",{value:!0}),e.TextareaEditor=void 0;var t=r;Object.defineProperty(e,"TextareaEditor",{enumerable:!0,get:function(){return t.TextareaEditor}})}(o);var c=o.TextareaEditor,f=o.__esModule;export{c as TextareaEditor,f as __esModule,o as default};
//# sourceMappingURL=/sm/580ae5926f419b406b57deb5004441d265da52848ed3a0725feeff21f5d0eb12.map