<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajouter', 'type'=>$this->types['enfant']));?>">Ajouter un nouveau <?php echo $this->types['enfant']; ?></a></p>
<table>
    <tr>
<?php foreach($this->cols as $col) : ?>
        <th><?php echo $col;?></th>
<?php endforeach; ?>
    </tr>  
<?php foreach($this->enfants as $enfant) : ?>
    <tr>
	<?php foreach($this->cols as $col) : ?>
        <td><?php echo $this->escape($enfant[$col]);?></td>
	<?php endforeach; ?>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'modifier', 'id'=>$enfant[$this->key[1]], 'type'=>$this->types['enfant']));?>">Modifier</a>
            <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'supprimer', 'id'=>$enfant[$this->key[1]], 'type'=>$this->types['enfant']));?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>