<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajouter', 'type'=>$this->types['enfant']));?>"><?php echo $this->libAjout; ?></a></p>
<div>
<?php echo $this->form ;?>
</div>
<br/>
<table>
    <tr>
<?php foreach($this->cols as $col) : ?>
        <th><?php echo $col;?></th>
<?php endforeach; ?>
    </tr>  
<?php foreach($this->enfants as $enfant) : ?>
    <tr>
	<?php foreach($this->cols as $col) : ?>
        <td><?php echo $this->escape($enfant[$col]);?></td>
	<?php endforeach; ?>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'modifier', 'type'=>$this->types['enfant'], 'id'=>$enfant[$this->key[1]]));?>">Modifier</a>
            <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'supprimer', 'type'=>$this->types['enfant'], 'id'=>$enfant[$this->key[1]]));?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>