<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'));?>">Retour à la liste des dictionnaires</a></p>
<p>Êtes-vous sûr de vouloir sauvegarder dans la BDD la version XML du dictionnaire de <?php echo $this->dico['type']; ?> : <a href="<?php echo $this->dico['url']; ?>"><?php echo $this->dico['url']; ?></a> ?
<br/>le temps de traitement peut être important.
</p>
<form action="<?php echo $this->url(array('action'=>'sauvegarder')); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $this->dico['id_dico']; ?>" />
    <input type="submit" name="sauvegarder" value="Oui" />
    <input type="submit" name="sauvegarder" value="Non" />
</div>
</form>