<?php 
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>    
</head>
<body>
    <div id="content">
        <h1><?php echo $this->escape($this->title); ?></h1>        
<?php 
if($this->types['parent']=="dico"){
	$urlR = $this->url(array('controller'=>'index', 'action'=>'index'),"",true);
	$urlR = '<a href="'.$urlR.'">Retour à la liste des '.$this->types['parent'].'s</a>';
	if($this->parent)
		$desc = $this->types['parent'].' de '.$this->parent['type'].' : <a href="'.$this->parent['url'].'" >'.$this->parent['url'].'</a>';
}
if($this->types['parent']=="conjugaison"){
	$urlR = $this->url(array('controller'=>'index', 'action'=>'modifier', 'type'=>'dico', 'id'=>$this->parent['id_dico']),"",true);
	$urlR = '<a href="'.$urlR.'">Retour à la liste des '.$this->types['parent'].'s</a>';
	$desc = $this->types['parent'].' : '.$this->parent['modele'].' ('.$this->parent['num'].')';
}
if($this->types['parent']=="terminaison"){
	$urlR = $this->url(array('controller'=>'index', 'action'=>'modifier', 'type'=>'verbe', 'id'=>$this->parent['id_verbe']),"",true);
	$urlR = '<a href="'.$urlR.'">Retour à la liste des '.$this->types['parent'].'s</a>';
	$desc = $this->types['parent'].' : '.$this->parent['lib'].' ('.$this->parent['num'].')';
}
if($this->types['parent']=="complement"
	|| $this->types['parent']=="determinant"
	|| $this->types['parent']=="syntagme"
	){
	$urlR = $this->url(array('controller'=>'index', 'action'=>'modifier', 'type'=>'dico', 'id'=>$this->parent['id_dico']),"",true);
	$urlR = '<a href="'.$urlR.'">Retour à la liste des '.$this->types['parent'].'s</a>';
	$desc = $this->types['parent'].' : '.$this->parent['lib'].' ('.$this->parent['num'].')';
}

?>
		<p><?php echo $urlR;?></p>
		<p><?php echo $desc;?></p>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>
